version: '3.8'

services:
  user_service:
    build: ./microservice-users
    ports:
      - "8001:8001"
    networks:
      - app-network

  finance_service:
    build: ./insurance-market-statistics
    ports:
      - "8000:8000"
    networks:
      - app-network

  api_gateway:
    image: nginx:latest
    volumes:
      - ./api_gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - user_service
      - finance_service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
