version: '3.8'

services:
  service_users:
    build: ../service_users
    ports:
      - "8001:8001"
    networks:
      - app-network

    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - DATABASE_URL=postgresql://postgres:3919305001@192.168.100.200:5432/dbfastapi

  service_finance:
    build: ../service_finance
    ports:
      - "8000:8000"
    networks:
      - app-network

    environment:
      - PUBLIC_KEY=${PUBLIC_KEY}

  API_GATEWAY:
    image: nginx:latest
    volumes:
      - ../API_GATEWAY/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - service_users
      - service_finance
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
